SELECT ROWID
     , EMPLOYEE_ID
  FROM EMPLOYEES;

SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

-- 실행 계획을 보기 위한 Oracle 구문
EXPLAIN PLAN
SET STATEMENT_ID = 'PLAN1' INTO PLAN_TABLE FOR
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , DEPARTMENT_ID
     , (SELECT DEPARTMENT_NAME FROM DEPARTMENTS B WHERE B.DEPARTMENT_ID = A.DEPARTMENT_ID) AS 부서명
     , (SELECT JOB_TITLE FROM JOBS C WHERE C.JOB_ID = A.JOB_ID) AS 직무명
  FROM EMPLOYEES A
 WHERE DEPARTMENT_ID IS NOT NULL;
SELECT STATEMENT_ID 실행계획명, PLAN_ID 계획ID
     , ID, PARENT_ID 상위ID
     , DEPTH 깊이, POSITION
     , OPERATION || ' ' || OPTIONS 실행내용
     , COST 비용
     , CARDINALITY 조회수
     , BYTES 용량
     , TIME 시간
  FROM PLAN_TABLE
 WHERE STATEMENT_ID = 'PLAN1';


EXPLAIN PLAN
SET STATEMENT_ID = 'PLAN2' INTO PLAN_TABLE FOR
SELECT A.EMPLOYEE_ID
     , A.FIRST_NAME
     , A.LAST_NAME
     , A.DEPARTMENT_ID
     , C.DEPARTMENT_NAME AS 부서명
     , B.JOB_TITLE AS 직무명
  FROM EMPLOYEES A JOIN JOBS B
    ON A.JOB_ID = B.JOB_ID
  JOIN DEPARTMENTS C
    ON A.DEPARTMENT_ID = C.DEPARTMENT_ID;
SELECT STATEMENT_ID 실행계획명, PLAN_ID 계획ID
     , ID, PARENT_ID 상위ID
     , DEPTH 깊이, POSITION
     , OPERATION || ' ' || OPTIONS 실행내용
     , COST 비용
     , CARDINALITY 조회수
     , BYTES 용량
     , TIME 시간
  FROM PLAN_TABLE
 WHERE STATEMENT_ID = 'PLAN2';

SELECT * FROM PLAN_TABLE;
